'use client';

import { type ReactNode } from 'react';
import { useCardFlip } from './CardFlipContext';

/**
 * The two-column dashboard grid (left: schedule/inbox/… · right: open tasks).
 * Default is an even split. Whenever the right card is flipped to a working
 * view — a task-plan step runner, a reply/compose editor, or an appointment
 * detail — the right side gets more room (30/70) so the canvas/editor isn't
 * cramped. With nothing flipped, it stays the original even layout.
 *
 * Uses a 10-col grid + col-span (standard utilities, always generated by
 * Tailwind) rather than an arbitrary `grid-cols-[3fr_7fr]`, which the JIT can
 * miss under HMR. Mobile stays single-column (no md: span → full width).
 */
export function DashboardGrid({ left, right }: { left: ReactNode; right: ReactNode }) {
  const { target } = useCardFlip();
  const flipped = !!target;

  return (
    <div className="grid grid-cols-1 gap-4 md:grid-cols-10">
      <div className={flipped ? 'md:col-span-3' : 'md:col-span-5'}>{left}</div>
      <div className={flipped ? 'md:col-span-7' : 'md:col-span-5'}>{right}</div>
    </div>
  );
}
