'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { BillRowActions } from './BillRowActions';

type BillFilter = 'outstanding' | 'overdue' | 'due30' | 'paid_month';
type BillRow = { id: string; billNumber: string | null; billDate: string; dueDate: string | null; status: string; memo: string | null; contactName: string | null; grossTotal: number; appliedTotal: number; outstanding: number };
type BillsSummary = { outstandingTotal: number; openCount: number; overdueTotal: number; dueIn30Total: number; paidThisMonth: number; agingCurrent: number; aging30: number; aging60: number; aging90: number; aging90Plus: number };
type Payload = { page: number; pageCount: number; totalCount: number; filter: BillFilter | null; today: string; in30: string; monthStart: string; summary: BillsSummary; rows: BillRow[]; agingTotal: number };
const FILTER_LABELS: Record<BillFilter, string> = { outstanding: 'Outstanding', overdue: 'Overdue', due30: 'Due in next 30 days', paid_month: 'Paid this month' };
const fmt = (n: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(n);
const fmtCompact = (n: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', notation: Math.abs(n) >= 10000 ? 'compact' : 'standard', maximumFractionDigits: Math.abs(n) >= 10000 ? 1 : 2 }).format(n);

export function BillsClient({ query }: { query: string }) {
  const [payload, setPayload] = useState<Payload | null>(null);
  const [error, setError] = useState(false);
  useEffect(() => {
    let cancelled = false;
    setPayload(null); setError(false);
    fetch(`/api/bills/summary${query}`, { headers: { Accept: 'application/json' } })
      .then((res) => res.ok ? res.json() : Promise.reject(new Error(`status ${res.status}`)))
      .then((data: Payload) => { if (!cancelled) setPayload(data); })
      .catch(() => { if (!cancelled) setError(true); });
    return () => { cancelled = true; };
  }, [query]);
  if (error) return <p className="text-sm text-amber-600">Bills are still loading. Refresh if this persists.</p>;
  if (!payload) return <BillsSkeleton />;
  const p = payload;
  return <><div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4"><Tile label="Outstanding" value={p.summary.outstandingTotal} tone="zinc" hint={`${p.summary.openCount} unpaid`} filter="outstanding" activeFilter={p.filter} /><Tile label="Overdue" value={p.summary.overdueTotal} tone={p.summary.overdueTotal > 0 ? 'red' : 'zinc'} hint={p.summary.overdueTotal > 0 ? 'Past due' : 'Nothing past due'} filter="overdue" activeFilter={p.filter} /><Tile label="Due in next 30 days" value={p.summary.dueIn30Total} tone="amber" hint={`${p.today} → ${p.in30}`} filter="due30" activeFilter={p.filter} /><Tile label="Paid this month" value={p.summary.paidThisMonth} tone="emerald" hint={`Since ${p.monthStart}`} filter="paid_month" activeFilter={p.filter} /></div>{p.filter && <div className="flex items-center gap-2 text-sm text-zinc-600 dark:text-zinc-400"><span>Filtering to <strong>{FILTER_LABELS[p.filter]}</strong> · {p.totalCount.toLocaleString()} match{p.totalCount === 1 ? '' : 'es'}</span><Link href="/bills" prefetch={false} className="rounded-md border border-zinc-300 px-2 py-0.5 text-xs hover:bg-zinc-100 dark:border-zinc-700 dark:hover:bg-zinc-900">Clear filter</Link></div>}{p.agingTotal > 0 && <AgingBar summary={p.summary} agingTotal={p.agingTotal} />}<BillsTable rows={p.rows} today={p.today} />{p.pageCount > 1 && <nav className="flex items-center gap-2 text-sm">{p.page > 1 && <a href={`?page=${p.page - 1}${p.filter ? `&filter=${p.filter}` : ''}`} className="rounded-md border border-zinc-300 px-3 py-1.5 hover:bg-zinc-100 dark:border-zinc-700 dark:hover:bg-zinc-900">← Previous</a>}{p.page < p.pageCount && <a href={`?page=${p.page + 1}${p.filter ? `&filter=${p.filter}` : ''}`} className="rounded-md border border-zinc-300 px-3 py-1.5 hover:bg-zinc-100 dark:border-zinc-700 dark:hover:bg-zinc-900">Next →</a>}</nav>}</>;
}
function BillsSkeleton() { return <div className="space-y-3">{Array.from({ length: 5 }).map((_, i) => <div key={i} className="h-16 animate-pulse rounded-lg bg-zinc-100 dark:bg-zinc-900" />)}</div>; }
function Tile({ label, value, tone, hint, filter, activeFilter }: { label: string; value: number; tone: 'zinc' | 'red' | 'amber' | 'emerald'; hint?: string; filter: BillFilter; activeFilter: BillFilter | null }) { const isActive = activeFilter === filter; const palette = { zinc: 'border-zinc-200 bg-white dark:border-zinc-800 dark:bg-zinc-950', red: 'border-red-300 bg-red-50 dark:border-red-800 dark:bg-red-900/20', amber: 'border-amber-300 bg-amber-50 dark:border-amber-800 dark:bg-amber-900/20', emerald: 'border-emerald-300 bg-emerald-50 dark:border-emerald-800 dark:bg-emerald-900/20' }[tone]; return <Link href={isActive ? '/bills' : `/bills?filter=${filter}`} prefetch={false} aria-pressed={isActive} className={`block rounded-lg border p-4 transition-shadow hover:shadow-md ${palette} ${isActive ? 'ring-2 ring-offset-1 dark:ring-offset-zinc-950 ring-zinc-400' : ''}`}><div className="text-xs uppercase tracking-wide text-zinc-600 dark:text-zinc-400">{label}</div><div className="mt-1 text-2xl font-semibold tabular-nums">{fmtCompact(value)}</div>{hint && <div className="mt-1 text-xs text-zinc-500">{hint}</div>}</Link>; }
function AgingBar({ summary, agingTotal }: { summary: BillsSummary; agingTotal: number }) { return <section className="rounded-lg border border-zinc-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-950"><header className="mb-3 flex items-center justify-between"><h2 className="text-sm font-medium uppercase tracking-wide text-zinc-600 dark:text-zinc-400">A/P aging</h2><span className="text-xs text-zinc-500">Total {fmt(agingTotal)}</span></header><div className="flex h-3 overflow-hidden rounded-full bg-zinc-100 dark:bg-zinc-800">{[{ amt: summary.agingCurrent, cls: 'bg-emerald-400' }, { amt: summary.aging30, cls: 'bg-amber-400' }, { amt: summary.aging60, cls: 'bg-orange-500' }, { amt: summary.aging90, cls: 'bg-red-500' }, { amt: summary.aging90Plus, cls: 'bg-red-700' }].map((seg, i) => seg.amt > 0 ? <div key={i} className={seg.cls} style={{ width: `${(seg.amt / agingTotal) * 100}%` }} title={fmt(seg.amt)} /> : null)}</div></section>; }
function BillsTable({ rows, today }: { rows: BillRow[]; today: string }) { return <div className="overflow-hidden rounded-lg border border-zinc-200 bg-white dark:border-zinc-800 dark:bg-zinc-950"><table className="w-full text-sm"><thead className="bg-zinc-50 text-left dark:bg-zinc-900"><tr><th className="px-4 py-2 text-xs font-medium uppercase tracking-wide text-zinc-500">Date</th><th className="px-4 py-2 text-xs font-medium uppercase tracking-wide text-zinc-500">Due</th><th className="px-4 py-2 text-xs font-medium uppercase tracking-wide text-zinc-500">Number</th><th className="px-4 py-2 text-xs font-medium uppercase tracking-wide text-zinc-500">Vendor</th><th className="px-4 py-2 text-xs font-medium uppercase tracking-wide text-zinc-500">Status</th><th className="px-4 py-2 text-right text-xs font-medium uppercase tracking-wide text-zinc-500">Outstanding</th><th className="px-4 py-2 text-xs font-medium uppercase tracking-wide text-zinc-500">Memo</th><th className="px-4 py-2 text-right"><span className="sr-only">Actions</span></th></tr></thead><tbody>{rows.length === 0 && <tr><td colSpan={8} className="px-4 py-6 text-center text-zinc-500">No bills.</td></tr>}{rows.map((b) => { const isOverdue = !!b.dueDate && b.dueDate < today && b.outstanding > 0; const statusLabel = b.status === 'posted' ? (b.outstanding <= 0 && b.appliedTotal > 0 ? 'paid' : isOverdue ? 'overdue' : b.appliedTotal > 0 ? 'partial' : 'posted') : (b.status ?? 'draft'); return <tr key={b.id} className="border-t border-zinc-100 hover:bg-zinc-50 dark:border-zinc-800 dark:hover:bg-zinc-900"><td className="px-4 py-2 tabular-nums text-zinc-700 dark:text-zinc-300"><Link href={`/bills/${b.id}`} prefetch={false} className="hover:underline">{b.billDate}</Link></td><td className="px-4 py-2 tabular-nums text-zinc-700 dark:text-zinc-300">{b.dueDate ?? '—'}</td><td className="px-4 py-2 text-zinc-700 dark:text-zinc-300">{b.billNumber ?? '—'}</td><td className="px-4 py-2 text-zinc-700 dark:text-zinc-300">{b.contactName ?? '—'}</td><td className="px-4 py-2"><StatusPill status={statusLabel} /></td><td className="px-4 py-2 text-right tabular-nums">{b.outstanding > 0 ? <span className={isOverdue ? 'font-medium text-red-600 dark:text-red-400' : 'text-zinc-700 dark:text-zinc-300'}>{fmt(b.outstanding)}</span> : <span className="text-zinc-400">—</span>}</td><td className="px-4 py-2 text-zinc-700 dark:text-zinc-300">{b.memo ?? '—'}</td><td className="px-4 py-2"><BillRowActions billId={b.id} billLabel={b.billNumber ?? `#${b.id.slice(0, 8)}`} /></td></tr>; })}</tbody></table></div>; }
function StatusPill({ status }: { status: string }) { const cls = { draft: 'bg-zinc-100 text-zinc-700 dark:bg-zinc-800 dark:text-zinc-300', posted: 'bg-blue-100 text-blue-800 dark:bg-blue-900/40 dark:text-blue-200', paid: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-900/40 dark:text-emerald-200', void: 'bg-zinc-200 text-zinc-600 line-through dark:bg-zinc-800 dark:text-zinc-500', overdue: 'bg-red-100 text-red-800 dark:bg-red-900/40 dark:text-red-200', partial: 'bg-amber-100 text-amber-800 dark:bg-amber-900/40 dark:text-amber-200' }[status.toLowerCase()] ?? 'bg-blue-100 text-blue-800 dark:bg-blue-900/40 dark:text-blue-200'; return <span className={`inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium uppercase tracking-wide ${cls}`}>{status}</span>; }
