import 'server-only';
import { Document, Page, View, Text, StyleSheet } from '@react-pdf/renderer';
import type { Form1099FilingData, Form1099Recipient } from './form-1099-filings';

const C = {
  ink: '#0f172a',
  body: '#1f2937',
  muted: '#64748b',
  line: '#0f172a',
  faint: '#94a3b8',
  band: '#f1f5f9',
};

const fmt = (n: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(n);

const s = StyleSheet.create({
  page: { paddingTop: 40, paddingBottom: 48, paddingHorizontal: 48, fontFamily: 'Helvetica', fontSize: 9, color: C.body },
  hdr: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: 6 },
  formTitle: { fontFamily: 'Helvetica-Bold', fontSize: 13, color: C.ink },
  formSub: { fontSize: 8.5, color: C.muted, marginTop: 2 },
  yearBox: { borderWidth: 1, borderColor: C.line, paddingVertical: 4, paddingHorizontal: 10, alignItems: 'center' },
  yearLabel: { fontSize: 7, color: C.muted },
  yearVal: { fontFamily: 'Helvetica-Bold', fontSize: 16, color: C.ink },
  copyTag: { fontFamily: 'Helvetica-Bold', fontSize: 8, color: C.muted, marginTop: 2 },
  rule: { borderBottomWidth: 1.25, borderBottomColor: C.line, marginVertical: 8 },
  row: { flexDirection: 'row' },
  colL: { width: '58%', paddingRight: 8 },
  colR: { width: '42%' },
  box: { borderWidth: 0.75, borderColor: C.line, padding: 6, marginBottom: 6, minHeight: 34 },
  boxLabel: { fontSize: 7, color: C.muted, marginBottom: 3 },
  boxVal: { fontSize: 10, color: C.ink },
  boxValBold: { fontFamily: 'Helvetica-Bold', fontSize: 13, color: C.ink },
  amtBox: { borderWidth: 1, borderColor: C.line, padding: 8, marginBottom: 6, minHeight: 44 },
  small: { fontSize: 8.5, color: C.body },
  footer: { position: 'absolute', bottom: 28, left: 48, right: 48, fontSize: 7.5, color: C.faint, borderTopWidth: 0.5, borderTopColor: C.faint, paddingTop: 6 },
  emptyWrap: { marginTop: 120, alignItems: 'center' },
  emptyText: { fontSize: 12, color: C.muted },
});

function Box({ label, children, bold }: { label: string; children: React.ReactNode; bold?: boolean }) {
  return (
    <View style={s.box}>
      <Text style={s.boxLabel}>{label}</Text>
      <Text style={bold ? s.boxValBold : s.boxVal}>{children}</Text>
    </View>
  );
}

function RecipientPage({ data, r }: { data: Form1099FilingData; r: Form1099Recipient }) {
  const payerBlock = [data.payer.name, data.payer.address.line1, data.payer.address.line2, data.payer.phone ? `Phone: ${data.payer.phone}` : '']
    .filter(Boolean)
    .join('\n');
  return (
    <Page size="A4" style={s.page}>
      <View style={s.hdr}>
        <View>
          <Text style={s.formTitle}>Form 1099-NEC</Text>
          <Text style={s.formSub}>Nonemployee Compensation</Text>
        </View>
        <View style={s.yearBox}>
          <Text style={s.yearLabel}>For calendar year</Text>
          <Text style={s.yearVal}>{data.year}</Text>
        </View>
        <View style={{ alignItems: 'flex-end' }}>
          <Text style={s.copyTag}>COPY B</Text>
          <Text style={s.formSub}>For Recipient (draft)</Text>
        </View>
      </View>
      <View style={s.rule} />

      <View style={s.row}>
        <View style={s.colL}>
          <View style={[s.box, { minHeight: 64 }]}>
            <Text style={s.boxLabel}>PAYER&apos;S name, address, ZIP, phone</Text>
            <Text style={s.boxVal}>{payerBlock || '—'}</Text>
          </View>
          <View style={s.row}>
            <View style={{ width: '50%', paddingRight: 4 }}>
              <Box label="PAYER'S TIN">{data.payer.tin || '—'}</Box>
            </View>
            <View style={{ width: '50%' }}>
              <Box label="RECIPIENT'S TIN">{r.tin || '—'}</Box>
            </View>
          </View>
          <Box label="RECIPIENT'S name">{r.name}</Box>
          <View style={[s.box, { minHeight: 48 }]}>
            <Text style={s.boxLabel}>RECIPIENT&apos;S address</Text>
            <Text style={s.boxVal}>{[r.address.line1, r.address.line2].filter(Boolean).join('\n') || '—'}</Text>
          </View>
        </View>

        <View style={s.colR}>
          <View style={s.amtBox}>
            <Text style={s.boxLabel}>1  Nonemployee compensation</Text>
            <Text style={s.boxValBold}>{fmt(r.amount)}</Text>
          </View>
          <View style={s.amtBox}>
            <Text style={s.boxLabel}>4  Federal income tax withheld</Text>
            <Text style={s.boxValBold}>{fmt(0)}</Text>
          </View>
          <View style={s.box}>
            <Text style={s.boxLabel}>Account number</Text>
            <Text style={s.boxVal}>{r.contactId.slice(0, 12)}</Text>
          </View>
        </View>
      </View>

      <Text style={s.footer}>
        Draft generated by {data.payer.name}. This is a recipient/record copy for review. Copy A must be filed with the IRS on the
        official scannable form or e-filed (IRS FIRE / IRIS). Box 4 assumes no backup withholding. Verify all amounts and TINs before filing.
      </Text>
    </Page>
  );
}

export function Form1099NecPdf(data: Form1099FilingData) {
  return (
    <Document title={`1099-NEC ${data.year}`}>
      {data.recipients.length === 0 ? (
        <Page size="A4" style={s.page}>
          <View style={s.emptyWrap}>
            <Text style={s.emptyText}>No 1099-eligible vendors met the {fmt(data.threshold)} threshold for {data.year}.</Text>
          </View>
        </Page>
      ) : (
        data.recipients.map((r) => <RecipientPage key={r.contactId} data={data} r={r} />)
      )}
    </Document>
  );
}
